name: ESLint Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x, x.x]

    steps:
      - uses: hallee/eslint-action@1.0.1
        with:
          # Commit message
          commit_message: ESLinted Code! # optional, default is Prettified Code!
